services:
  - type: web
    name: svl-backend
    runtime: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
